CMakeLists: Fix cross-compilation error with DSO symbols
When I cross-compile with OpenIPC/Buildroot I get an error with DSO symbols:

/data_drive/omlet/OpenIPC-firmware/output/per-package/antmedia-gstreamer-webrtc/host/mipsel-buildroot-linux-gnu/sysroot/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/sendRecvAnt.dir/build.make:98: sendRecvAnt] Error 1
make[4]: *** [CMakeFiles/Makefile2:121: CMakeFiles/sendRecvAnt.dir/all] Error 2
make[3]: *** [Makefile:156: all] Error 2

This post gives a solution: https://stackoverflow.com/questions/8725572/gcc-4-5-vs-4-4-linking-with-dependencies

Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>